Upgrade to Angular 10
fundsaccess/angular-iban pull request #12
Opened 2020-10-02 19:02 UTC by Aracturat

Upgrade this library to support Angular 10. Please publish it after accept.

2020-10-03 14:53 UTC, WuglyakBolgoink requested changes

2020-10-03 14:53 UTC, WuglyakBolgoink commented on projects/angular-iban/package.json
> -  "license": "MIT"
@Aracturat Tnx, но "license" нужна для npm-registry.

2020-10-03 15:01 UTC, Aracturat commented on projects/angular-iban/package.json
> -  "license": "MIT"
Уппс, случайно снес, сейчас верну

2020-10-03 18:19 UTC, Aracturat commented
@WuglyakBolgoink Fixed license file

2020-10-05 14:14 UTC, Aracturat commented
@fundsaccess can you look at this PR?

2020-10-06 19:38 UTC, fundsaccess commented
Hello @Aracturat,

thanks for your PR.  We will review it and give you feedback.

Kind regards,
fundsaccess F/E team

2020-10-09 21:34 UTC, fundsaccess approved these changes
Hi @Aracturat ,

thank you so much for this PR. It's looking very good. Just a suggestion for the future, before you would contribute to this project, please create an issue and let's talk about it at first. Minor fixes or improvements that don't have with the upgrade to do should be handled in separate issues and PRs. 

We are looking forward to your next contribution! 

Kind regards,
fundsaccess F/E Team

2020-10-09 21:53 UTC, merged